language: python
python:
    - "3.6"

services:
    - docker

before_script: pip install docker-compose

script:
    - docker-compose run \
        -e DJANGO_SETTINGS_MODULE=app.settings.testing \
        --no-deps --rm app py.test;